development:
  adapter: postgresql
  encoding: unicode
  database: private_event
  pool: 5
  username: addo
  password: qafqaf

test:
  adapter: postgresql
  encoding: unicode
  database: private_event
  pool: 5
  username: addo
  password: qafqaf